dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /var/lib/mysql

redis:
  image: redis

db:
  image: million12/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: pass

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - data:/data
#    - Persistent:/data/www/boilerplate.local/surf/shared/Data/Persistent
    - /etc/localtime:/etc/localtime:ro

web:
  image: dimaip/boilerplatedistr:latest
  ports:
    - '80'
  links:
    - db:db
    - redis
  volumes_from:
    - webdata
  environment:
    VIRTUAL_HOST: 'boilerplate.local,dev.boilerplate.local,next.boilerplate.local'
    T3APP_NAME: 'boilerplate.local'

ssh:
  image: million12/php-app-ssh
  ports:
    - '22'
  links:
    - db:db
    - redis
    - web:web
  volumes_from:
    - webdata
  environment:
    IMPORT_GITHUB_PUB_KEYS: dimaip

