rules:
  indentation:
    - 1
    -
      size: 1
  class-name-format: 0
  variable-name-format: 0
  placeholder-in-extend: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-important: 0
  space-around-operator: 0
  clean-import-paths: 0
  property-sort-order:
    - 1
    -
      order: 'concentric'
